# Generated by Django 5.1.6 on 2025-02-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='bild',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='mitarbeiter_bilder/'),
        ),
    ]
