# Generated by Django 5.1.6 on 2025-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausrüstung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausrüstung',
            name='preis',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
