# Generated by Django 4.2.19 on 2025-02-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ausrüstung', '0002_alter_ausrüstung_preis'),
        ('ausrüstung', '0002_product_delete_ausrüstung'),
    ]

    operations = [
    ]
